import AuthProvider from "@/Providers/AuthProvider";
import QueryClientProviderWrapper from "@/Providers/QueryclientProvider";
import SocketProvider from "@/Providers/SocketProvider";
import StyleProvider from "@/Providers/StyleProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <QueryClientProviderWrapper>
        <AuthProvider>
          <SocketProvider>
            <StyleProvider>
              <body className={inter.className}>
                <ToastContainer />
                {children}
              </body>
            </StyleProvider>
          </SocketProvider>
        </AuthProvider>
      </QueryClientProviderWrapper>
    </html>
  );
}
